const ASSET_AVAILABILITY = {
  AVAILABLE: 'AVAILABLE',
  BOOKED: 'BOOKED',
  UNAVAILABLE: 'UNAVAILABLE',
};

const RENTAL_STATUS = {
  REQUESTED: 'REQUESTED',
  NEGOTIATING: 'NEGOTIATING',
  ACCEPTED: 'ACCEPTED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

const NOTIFICATION_TYPE = {
  REQUEST: 'REQUEST',
  COUNTER_OFFER: 'COUNTER_OFFER',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  GENERAL: 'GENERAL',
};

module.exports = { ASSET_AVAILABILITY, RENTAL_STATUS, NOTIFICATION_TYPE };
